// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bgsadvisor/v2/models"
)

// GetStationsReader is a Reader for the GetStations structure.
type GetStationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetStationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetStationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetStationsOK creates a GetStationsOK with default headers values
func NewGetStationsOK() *GetStationsOK {
	return &GetStationsOK{}
}

/* GetStationsOK describes a response with status code 200, with default header values.

An array of stations with historical data
*/
type GetStationsOK struct {
	Payload []*models.EBGSStationsPageV5
}

func (o *GetStationsOK) Error() string {
	return fmt.Sprintf("[GET /stations][%d] getStationsOK  %+v", 200, o.Payload)
}
func (o *GetStationsOK) GetPayload() []*models.EBGSStationsPageV5 {
	return o.Payload
}

func (o *GetStationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
