// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSFactionsPageV5 e b g s factions page v5
//
// swagger:model EBGSFactionsPageV5
type EBGSFactionsPageV5 struct {

	// docs
	Docs []*EBGSFactionsV5 `json:"docs"`

	// limit
	Limit int64 `json:"limit,omitempty"`

	// page
	Page int64 `json:"page,omitempty"`

	// pages
	Pages int64 `json:"pages,omitempty"`

	// total
	Total int64 `json:"total,omitempty"`
}

// Validate validates this e b g s factions page v5
func (m *EBGSFactionsPageV5) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDocs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionsPageV5) validateDocs(formats strfmt.Registry) error {
	if swag.IsZero(m.Docs) { // not required
		return nil
	}

	for i := 0; i < len(m.Docs); i++ {
		if swag.IsZero(m.Docs[i]) { // not required
			continue
		}

		if m.Docs[i] != nil {
			if err := m.Docs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this e b g s factions page v5 based on the context it is used
func (m *EBGSFactionsPageV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDocs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionsPageV5) contextValidateDocs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Docs); i++ {

		if m.Docs[i] != nil {
			if err := m.Docs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("docs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EBGSFactionsPageV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSFactionsPageV5) UnmarshalBinary(b []byte) error {
	var res EBGSFactionsPageV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
