// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSConflictFactionV5 e b g s conflict faction v5
//
// swagger:model EBGSConflictFactionV5
type EBGSConflictFactionV5 struct {

	// days won
	DaysWon int64 `json:"days_won,omitempty"`

	// opponent faction id
	OpponentFactionID string `json:"opponent_faction_id,omitempty"`

	// opponent name
	OpponentName string `json:"opponent_name,omitempty"`

	// opponent name lower
	OpponentNameLower string `json:"opponent_name_lower,omitempty"`

	// stake
	Stake string `json:"stake,omitempty"`

	// stake lower
	StakeLower string `json:"stake_lower,omitempty"`

	// station id
	StationID string `json:"station_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this e b g s conflict faction v5
func (m *EBGSConflictFactionV5) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e b g s conflict faction v5 based on context it is used
func (m *EBGSConflictFactionV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EBGSConflictFactionV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSConflictFactionV5) UnmarshalBinary(b []byte) error {
	var res EBGSConflictFactionV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
