// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSFactionRefV5 e b g s faction ref v5
//
// swagger:model EBGSFactionRefV5
type EBGSFactionRefV5 struct {

	// faction details
	FactionDetails *EBGSFactionsV5 `json:"faction_details,omitempty"`

	// faction id
	FactionID string `json:"faction_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// name lower
	NameLower string `json:"name_lower,omitempty"`
}

// Validate validates this e b g s faction ref v5
func (m *EBGSFactionRefV5) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFactionDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionRefV5) validateFactionDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.FactionDetails) { // not required
		return nil
	}

	if m.FactionDetails != nil {
		if err := m.FactionDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("faction_details")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this e b g s faction ref v5 based on the context it is used
func (m *EBGSFactionRefV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFactionDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionRefV5) contextValidateFactionDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.FactionDetails != nil {
		if err := m.FactionDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("faction_details")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *EBGSFactionRefV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSFactionRefV5) UnmarshalBinary(b []byte) error {
	var res EBGSFactionRefV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
