// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSSystemRefV5 e b g s system ref v5
//
// swagger:model EBGSSystemRefV5
type EBGSSystemRefV5 struct {

	// name
	Name string `json:"name,omitempty"`

	// name lower
	NameLower string `json:"name_lower,omitempty"`

	// system id
	SystemID string `json:"system_id,omitempty"`
}

// Validate validates this e b g s system ref v5
func (m *EBGSSystemRefV5) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e b g s system ref v5 based on context it is used
func (m *EBGSSystemRefV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EBGSSystemRefV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSSystemRefV5) UnmarshalBinary(b []byte) error {
	var res EBGSSystemRefV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
