// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSStateActiveV5 e b g s state active v5
//
// swagger:model EBGSStateActiveV5
type EBGSStateActiveV5 struct {

	// state
	State string `json:"state,omitempty"`
}

// Validate validates this e b g s state active v5
func (m *EBGSStateActiveV5) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e b g s state active v5 based on context it is used
func (m *EBGSStateActiveV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EBGSStateActiveV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSStateActiveV5) UnmarshalBinary(b []byte) error {
	var res EBGSStateActiveV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
