// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EBGSFactionHistorySystemV5 e b g s faction history system v5
//
// swagger:model EBGSFactionHistorySystemV5
type EBGSFactionHistorySystemV5 struct {

	// v
	V int64 `json:"__v,omitempty"`

	// id
	ID string `json:"_id,omitempty"`

	// active states
	ActiveStates []*EBGSStateActiveV5 `json:"active_states"`

	// conflicts
	Conflicts []*EBGSConflictFactionV5 `json:"conflicts"`

	// faction id
	FactionID string `json:"faction_id,omitempty"`

	// faction name
	FactionName string `json:"faction_name,omitempty"`

	// faction name lower
	FactionNameLower string `json:"faction_name_lower,omitempty"`

	// happiness
	Happiness string `json:"happiness,omitempty"`

	// influence
	Influence float64 `json:"influence,omitempty"`

	// pending states
	PendingStates []*EBGSStateV5 `json:"pending_states"`

	// recovering states
	RecoveringStates []*EBGSStateV5 `json:"recovering_states"`

	// state
	State string `json:"state,omitempty"`

	// systems
	Systems []*EBGSSystemRefV5 `json:"systems"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// updated by
	UpdatedBy string `json:"updated_by,omitempty"`
}

// Validate validates this e b g s faction history system v5
func (m *EBGSFactionHistorySystemV5) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActiveStates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConflicts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePendingStates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoveringStates(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSystems(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionHistorySystemV5) validateActiveStates(formats strfmt.Registry) error {
	if swag.IsZero(m.ActiveStates) { // not required
		return nil
	}

	for i := 0; i < len(m.ActiveStates); i++ {
		if swag.IsZero(m.ActiveStates[i]) { // not required
			continue
		}

		if m.ActiveStates[i] != nil {
			if err := m.ActiveStates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("active_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) validateConflicts(formats strfmt.Registry) error {
	if swag.IsZero(m.Conflicts) { // not required
		return nil
	}

	for i := 0; i < len(m.Conflicts); i++ {
		if swag.IsZero(m.Conflicts[i]) { // not required
			continue
		}

		if m.Conflicts[i] != nil {
			if err := m.Conflicts[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) validatePendingStates(formats strfmt.Registry) error {
	if swag.IsZero(m.PendingStates) { // not required
		return nil
	}

	for i := 0; i < len(m.PendingStates); i++ {
		if swag.IsZero(m.PendingStates[i]) { // not required
			continue
		}

		if m.PendingStates[i] != nil {
			if err := m.PendingStates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pending_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) validateRecoveringStates(formats strfmt.Registry) error {
	if swag.IsZero(m.RecoveringStates) { // not required
		return nil
	}

	for i := 0; i < len(m.RecoveringStates); i++ {
		if swag.IsZero(m.RecoveringStates[i]) { // not required
			continue
		}

		if m.RecoveringStates[i] != nil {
			if err := m.RecoveringStates[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovering_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) validateSystems(formats strfmt.Registry) error {
	if swag.IsZero(m.Systems) { // not required
		return nil
	}

	for i := 0; i < len(m.Systems); i++ {
		if swag.IsZero(m.Systems[i]) { // not required
			continue
		}

		if m.Systems[i] != nil {
			if err := m.Systems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("systems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this e b g s faction history system v5 based on the context it is used
func (m *EBGSFactionHistorySystemV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateActiveStates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConflicts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePendingStates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRecoveringStates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSystems(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EBGSFactionHistorySystemV5) contextValidateActiveStates(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ActiveStates); i++ {

		if m.ActiveStates[i] != nil {
			if err := m.ActiveStates[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("active_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) contextValidateConflicts(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Conflicts); i++ {

		if m.Conflicts[i] != nil {
			if err := m.Conflicts[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("conflicts" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) contextValidatePendingStates(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PendingStates); i++ {

		if m.PendingStates[i] != nil {
			if err := m.PendingStates[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pending_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) contextValidateRecoveringStates(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RecoveringStates); i++ {

		if m.RecoveringStates[i] != nil {
			if err := m.RecoveringStates[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovering_states" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *EBGSFactionHistorySystemV5) contextValidateSystems(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Systems); i++ {

		if m.Systems[i] != nil {
			if err := m.Systems[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("systems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EBGSFactionHistorySystemV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EBGSFactionHistorySystemV5) UnmarshalBinary(b []byte) error {
	var res EBGSFactionHistorySystemV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
