// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TickTimesHistoryV5 tick times history v5
//
// swagger:model TickTimesHistoryV5
type TickTimesHistoryV5 struct {

	// v
	V int64 `json:"__v,omitempty"`

	// id
	ID string `json:"_id,omitempty"`

	// time
	Time string `json:"time,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this tick times history v5
func (m *TickTimesHistoryV5) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tick times history v5 based on context it is used
func (m *TickTimesHistoryV5) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TickTimesHistoryV5) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TickTimesHistoryV5) UnmarshalBinary(b []byte) error {
	var res TickTimesHistoryV5
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
